version: "3.9"

services:
  geoalchemy-main:
    container_name: geoalchemy-${ENVIRONMENT}
    restart: always
    build:
      context: .
    working_dir: /usr/geoalchemy-main
    command: sh -c "
        alembic upgrade head &&
        python src/main.py
      "
    env_file: ./.env.${ENVIRONMENT}
    networks:
      - geoalchemy-network
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - geoalchemy-db
    healthcheck:
      test: curl -f http://localhost:${SERVER_PORT}/api/healthcheck
      interval: 60s
      timeout: 3s
      retries: 3

  geoalchemy-db:
    image: postgis/postgis:16-3.5-alpine
    container_name: geoalchemy-db-${ENVIRONMENT}
    restart: always
    command: -p ${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - geoalchemy-network
    expose:
      - ${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./data/geoalchemy-db-data-${ENVIRONMENT}:/var/lib/postgresql/data/
    healthcheck:
      test: pg_isready -p ${POSTGRES_PORT} -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 60s
      timeout: 3s
      retries: 3

networks:
  geoalchemy-network:
    name: geoalchemy-network-${ENVIRONMENT}
    driver: bridge
    external: false
